sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y apache2 
  - echo "ServerName localhost" >> /etc/apache2/apache2.conf

install:
  - composer install --dev --prefer-dist
  - cd integrationtestsettings
  - chmod +x install-test-env.sh
  - ./install-test-env.sh
  - ./start-apache2.sh
  - ./start-solr.sh &
  - ./start-fuseki.sh &
  - mysql < openskos-create.sql
  - ./openskos-init.sh
  - cd ..
  - ls

script:
 - ./vendor/bin/phpcs --standard=PSR2 library/OpenSkos2/
 - phpunit
