sudo: true

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - sudo apt-get update
  - sudo apt-get install apache2 -y
  - sudo service apache2 restart

install:
  - composer install --dev --prefer-dist
  - chmod -R ugo+rw cache
  - chmod -R ugo+rw data
  - chmod -R ugo+rw public/data
  - sudo rm -rf /var/www/html 
  - sudo ln -s /home/travis/build/OpenSKOS/OpenSKOS /var/www/html
  - cd integrationtestsettings
  - chmod +x install-test-env.sh
  - ./install-test-env.sh
  - ./start-solr.sh &
  - ./start-fuseki.sh &
  - mysql < openskos-create.sql
  - ./openskos-init.sh
  - cd ..
  - ls

script:
 - ./vendor/bin/phpcs --standard=PSR2 library/OpenSkos2/
 - phpunit
